# 1 "/home/drxiang/programming/Doiting_BL/bl_iot_sdk/components/network/ble/blestack/src/common/tinycrypt/source/ecc_platform_specific.c"
# 1 "/home/drxiang/programming/Doiting_BL/examples/WIFI_CLIENT/build_out/blestack//"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/home/drxiang/programming/Doiting_BL/bl_iot_sdk/components/network/ble/blestack/src/common/tinycrypt/source/ecc_platform_specific.c"
